namePrefix: kustomize-

resources:
- test.yml
- test-service.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: REPLACE_ME_APP_NAME
  newName: 890324431850.dkr.ecr.ap-south-1.amazonaws.com/data-platform-skn/demo
  newTag: 0.0.1
- name: REPLACE_ME_APP_NAME:890324431850.dkr.ecr.ap-south-1.amazonaws.com/data-platform-skn/demo
  newTag: 0.0.1
- name: REPLACE_ME_IMAGE_NAME
  newName: 890324431850.dkr.ecr.ap-south-1.amazonaws.com/demo
  newTag: f1fca22e9a1930e3e9a38ad277b2ee5d28a982ab
