apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
       - image: REPLACE_ME_IMAGE_NAME
         name: demo
         ports:
         - containerPort: 8080
      imagePullSecrets:
      - name: ecrcred1

